[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

lib_deps =
  adafruit/Adafruit SSD1306 @ ^2.5.7
  adafruit/Adafruit GFX Library @ ^1.11.3
  fastled/FastLED @ 3.5.0
  kosme/arduinoFFT @ ^2.0.2
  knolleary/PubSubClient @ ^2.8